https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [5]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.72126297, 0.12910365, 0.42181224, 0.4355853 ],
       [0.51524748, 0.70660521, 0.58100039, 0.14290127],
       [0.79652701, 0.35442967, 0.83700466, 0.43947087]])

In [7]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [13]:
#ndarray,陣列運算
normal_value * 10

array([[ -3.15005677, -17.96313322,  17.24481081, -11.86646606],
       [-24.10874927,  -9.25851207,  11.95982418,  -3.45211519],
       [ -9.6533045 ,  -1.06209999,  -2.91955132, -16.9679638 ]])

In [9]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-1.57348452, -2.48595524, -3.06029196])